
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drnqalhfkfzzjlowdnow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybnFhbGhma2Z6empsb3dkbm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTUzNDksImV4cCI6MjA1OTE3MTM0OX0.jjrIiO6Cn0g3yjteF-8RK-HbHUApJIxc-VYpINCPdkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
